name: Unittests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configs: [Release, Debug]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        config: ${{ matrix.configs }}
    - name: Run unittests
      run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            ./build/tests/unittests
          elif [ "$RUNNER_OS" == "Windows" ]; then
            ./build/tests/${{matrix.configs}}/unittests.exe
          fi